version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - ./database:/data/db
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  api:
    image: node:latest
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"